SELECT Username, CATEGORY.NAME, QUESTION,answer FROM APP_USER INNER JOIN STUDY_SET ON APP_USER.user_id = STUDY_SET.owner_id
INNER JOIN STUDY_SET_CARD ON STUDY_SET.study_set_id = STUDY_SET_CARD.study_set_id
INNER JOIN FLASHCARD ON STUDY_SET_CARD.flashcard_id = FLASHCARD.flashcard_id
INNER JOIN CATEGORY ON FLASHCARD.category_id = CATEGORY.category_id WHERE STUDY_SET.owner_id = 4;